import { Canvas, useFrame, useThree, type ThreeEvent } from "@react-three/fiber";
import { useEffect, useMemo, useRef } from "react";
import * as THREE from "three";
import { OrbitControls } from "three/examples/jsm/controls/OrbitControls.js";
import type { ExerciseAnnotation, ExerciseMarker, ExercisePath, ExerciseTool, ExerciseView } from "./exerciseTypes";

interface ExerciseCanvasProps { view:ExerciseView; tool:ExerciseTool; markers:ExerciseMarker[]; paths:ExercisePath[]; annotations:ExerciseAnnotation[]; selectedId:string|null; playing:boolean; onSelect:(id:string|null)=>void; onMove:(id:string,x:number,z:number)=>void; onPitchPointer:(phase:"down"|"move"|"up",x:number,z:number)=>void; onEraseAnnotation:(id:string)=>void; }
const W=12,H=8,LINE="#b8c8cc";

function CameraControls({view}:{view:ExerciseView}){const{camera,gl,size}=useThree();useEffect(()=>{if(view!=="3d")return;if(size.width/size.height<1.15)camera.position.set(0,9.2,12.7);const controls=new OrbitControls(camera,gl.domElement);controls.target.set(0,0,0);controls.enableDamping=true;controls.enableRotate=false;controls.enablePan=false;controls.minDistance=7;controls.maxDistance=18;controls.maxPolarAngle=Math.PI/2.1;const setCameraDrag=(enabled:boolean)=>{controls.enableRotate=enabled;controls.enablePan=enabled;};const keyDown=(event:KeyboardEvent)=>{if(event.key==="Shift")setCameraDrag(true);};const keyUp=(event:KeyboardEvent)=>{if(event.key==="Shift")setCameraDrag(false);};const blur=()=>setCameraDrag(false);window.addEventListener("keydown",keyDown);window.addEventListener("keyup",keyUp);window.addEventListener("blur",blur);controls.update();return()=>{window.removeEventListener("keydown",keyDown);window.removeEventListener("keyup",keyUp);window.removeEventListener("blur",blur);controls.dispose();};},[camera,gl,size.height,size.width,view]);return null;}

function PitchLine({points,color=LINE,y=.025}:{points:Array<[number,number]>;color?:string;y?:number}){const geometry=useMemo(()=>new THREE.BufferGeometry().setFromPoints(points.map(([x,z])=>new THREE.Vector3(x,y,z))),[points,y]);const material=useMemo(()=>new THREE.LineBasicMaterial({color,transparent:true,opacity:.96}),[color]);const line=useMemo(()=>new THREE.Line(geometry,material),[geometry,material]);useEffect(()=>()=>{geometry.dispose();material.dispose();},[geometry,material]);return <primitive object={line}/>;}
function arc(cx:number,cz:number,r:number,from:number,to:number,n=28):Array<[number,number]>{return Array.from({length:n+1},(_,i)=>{const a=from+(to-from)*i/n;return[cx+Math.cos(a)*r,cz+Math.sin(a)*r];});}
function Goal({x,flip=false}:{x:number;flip?:boolean}){const depth=flip?.48:-.48,back=x+depth,mid=x+depth/2;return <group>{[x,back].flatMap((postX,row)=>[-.78,.78].map(z=><mesh key={`${row}-${z}`} position={[postX,.18,z]}><boxGeometry args={[.035,.36,.035]}/><meshStandardMaterial color="#dce5e7"/></mesh>))}<mesh position={[x,.36,0]}><boxGeometry args={[.035,.035,1.6]}/><meshStandardMaterial color="#dce5e7"/></mesh><mesh position={[back,.36,0]}><boxGeometry args={[.035,.035,1.6]}/><meshStandardMaterial color="#dce5e7"/></mesh>{[-.78,.78].map(z=><mesh key={z} position={[mid,.36,z]}><boxGeometry args={[Math.abs(depth),.035,.035]}/><meshStandardMaterial color="#dce5e7"/></mesh>)}<mesh position={[back,.18,0]}><boxGeometry args={[.012,.35,1.55]}/><meshBasicMaterial color="#7d939d" wireframe transparent opacity={.55}/></mesh>{[-.78,.78].map(z=><mesh key={`net-${z}`} position={[mid,.18,z]}><boxGeometry args={[Math.abs(depth),.35,.012]}/><meshBasicMaterial color="#7d939d" wireframe transparent opacity={.45}/></mesh>)}</group>;}

function Pitch(){const center=useMemo(()=>arc(0,0,1.03,0,Math.PI*2,56),[]);return <group><mesh rotation={[-Math.PI/2,0,0]} receiveShadow><planeGeometry args={[W,H]}/><meshStandardMaterial color="#121d22" roughness={.96}/></mesh>{Array.from({length:10},(_,i)=><mesh key={i} rotation={[-Math.PI/2,0,0]} position={[-5.4+i*1.2,.006,0]}><planeGeometry args={[1.2,H]}/><meshBasicMaterial color={i%2?"#17252a":"#101a1f"}/></mesh>)}<PitchLine points={[[-5.75,-3.75],[5.75,-3.75],[5.75,3.75],[-5.75,3.75],[-5.75,-3.75]]}/><PitchLine points={[[0,-3.75],[0,3.75]]}/><PitchLine points={center}/>{[1,-1].map(side=>{const end=side*5.75,penalty=side*4.42,goal=side*5.18,spot=side*4.72;return <group key={side}><PitchLine points={[[end,-2.05],[penalty,-2.05],[penalty,2.05],[end,2.05]]}/><PitchLine points={[[end,-.9],[goal,-.9],[goal,.9],[end,.9]]}/><mesh position={[spot,.032,0]} rotation={[-Math.PI/2,0,0]}><circleGeometry args={[.045,18]}/><meshBasicMaterial color={LINE}/></mesh><PitchLine points={arc(spot,0,.8,side>0?Math.PI*.65:-Math.PI*.35,side>0?Math.PI*1.35:Math.PI*.35)}/></group>;})}{([[-5.75,-3.75,0,Math.PI/2],[5.75,-3.75,Math.PI/2,Math.PI],[-5.75,3.75,-Math.PI/2,0],[5.75,3.75,Math.PI,Math.PI*1.5]] as Array<[number,number,number,number]>).map(([x,z,a,b],i)=><PitchLine key={i} points={arc(x,z,.18,a,b,10)}/>)}<mesh position={[0,.032,0]} rotation={[-Math.PI/2,0,0]}><circleGeometry args={[.05,18]}/><meshBasicMaterial color={LINE}/></mesh><Goal x={-5.75}/><Goal x={5.75} flip/></group>;}
function Boards(){const boards=useMemo(()=>{const r:Array<{x:number;z:number;rot:number;w:number}>=[];for(let x=-5;x<=5;x+=2)r.push({x,z:-4.08,rot:0,w:1.82},{x,z:4.08,rot:0,w:1.82});for(let z=-3;z<=3;z+=1.5)if(z!==0)r.push({x:-6.08,z,rot:Math.PI/2,w:1.3},{x:6.08,z,rot:Math.PI/2,w:1.3});return r;},[]);return <group>{boards.map((b,i)=><mesh key={i} position={[b.x,.13,b.z]} rotation={[0,b.rot,0]}><boxGeometry args={[b.w,.28,.07]}/><meshStandardMaterial color={i%3===0?"#194263":"#162934"} emissive={i%3===0?"#0d3658":"#091820"} emissiveIntensity={.45}/></mesh>)}</group>;}

function textureFor(text:string){const canvas=document.createElement("canvas");canvas.width=320;canvas.height=88;const c=canvas.getContext("2d")!;c.font="700 28px Manrope, sans-serif";c.textAlign="center";const width=Math.min(300,c.measureText(text).width+32);c.fillStyle="rgba(6,15,21,.94)";c.roundRect((320-width)/2,5,width,48,11);c.fill();c.fillStyle="#fff";c.fillText(text,160,38);const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;return texture;}
function Marker({marker,selected,view,onPointerDown}:{marker:ExerciseMarker;selected:boolean;view:ExerciseView;onPointerDown:(id:string)=>void}){const texture=useMemo(()=>textureFor(marker.kind==="ball"?"Pallo":marker.name),[marker]);useEffect(()=>()=>texture.dispose(),[texture]);const color=marker.kind==="ball"?"#f3aa2b":marker.team==="red"?"#e14d46":"#2686d9";return <group position={[marker.x,.11,marker.z]} onPointerDown={(e:ThreeEvent<PointerEvent>)=>{if(e.shiftKey)return;e.stopPropagation();onPointerDown(marker.id);}}>{marker.kind==="ball"?<mesh castShadow={view==="3d"}><sphereGeometry args={[.145,24,24]}/><meshStandardMaterial color={color} emissive="#5b3700" emissiveIntensity={.25}/></mesh>:<><mesh castShadow={view==="3d"}><cylinderGeometry args={[.19,.19,.12,32]}/><meshStandardMaterial color={color} roughness={.4} emissive={selected?color:"#000"} emissiveIntensity={selected?.35:0}/></mesh><mesh position={[0,.065,0]} rotation={[-Math.PI/2,0,0]}><ringGeometry args={[.14,.18,32]}/><meshBasicMaterial color="#e8f1f4"/></mesh></>}{selected&&<mesh rotation={[-Math.PI/2,0,0]} position={[0,-.045,0]}><ringGeometry args={[.26,.31,36]}/><meshBasicMaterial color="#f3a712"/></mesh>}<sprite position={[0,.31,0]} scale={[1.35,.37,1]}><spriteMaterial map={texture} transparent depthTest={false}/></sprite></group>;}
function AnimatedPath({path,from,to,playing}:{path:ExercisePath;from:ExerciseMarker;to:ExerciseMarker;playing:boolean}){const pulse=useRef<THREE.Mesh|null>(null);const direction=useMemo(()=>new THREE.Vector3(to.x-from.x,0,to.z-from.z).normalize(),[from.x,from.z,to.x,to.z]);const curve=useMemo(()=>{const fromRadius=from.kind==="ball"?.18:.25,toRadius=to.kind==="ball"?.18:.25;return new THREE.LineCurve3(new THREE.Vector3(from.x,.12,from.z).addScaledVector(direction,fromRadius),new THREE.Vector3(to.x,.12,to.z).addScaledVector(direction,-toRadius));},[direction,from.kind,from.x,from.z,to.kind,to.x,to.z]);const color=path.kind==="pass"?"#ffb21c":"#75d7ff",rotation:[number,number,number]=[-Math.PI/2,0,-Math.atan2(direction.z,direction.x)+Math.PI/2],movingArrowRotation:[number,number,number]=[rotation[0],rotation[1],rotation[2]+Math.PI];useFrame(({clock})=>{if(pulse.current)pulse.current.position.copy(curve.getPoint(playing?(clock.elapsedTime*.48)%1:.5));});const end=curve.getPoint(1);return <group><mesh><tubeGeometry args={[curve,36,.035,8,false]}/><meshBasicMaterial color={color} transparent opacity={.9}/></mesh><mesh ref={pulse} rotation={path.kind==="run"?movingArrowRotation:undefined}>{path.kind==="pass"?<sphereGeometry args={[.085,16,16]}/>:<coneGeometry args={[.11,.23,3]}/>}<meshBasicMaterial color="#fff" toneMapped={false}/></mesh><mesh position={[end.x,end.y,end.z]} rotation={rotation}><coneGeometry args={[.11,.22,3]}/><meshBasicMaterial color={color}/></mesh></group>;}
function Annotation({item,erase,onErase}:{item:ExerciseAnnotation;erase:boolean;onErase:(id:string)=>void}){const click=(e:ThreeEvent<PointerEvent>)=>{if(erase){e.stopPropagation();onErase(item.id);}};if(item.kind==="text"){const texture=textureFor(item.text||"Teksti");return <sprite onPointerDown={click} position={[item.points[0]?.x||0,.16,item.points[0]?.z||0]} scale={[1.8,.5,1]}><spriteMaterial map={texture} transparent depthTest={false}/></sprite>;}const a=item.points[0],b=item.points.at(-1);if(!a||!b)return null;let points=item.points.map(p=>[p.x,p.z] as [number,number]);if(item.kind==="rectangle")points=[[a.x,a.z],[b.x,a.z],[b.x,b.z],[a.x,b.z],[a.x,a.z]];if(item.kind==="circle"){const rx=Math.abs(b.x-a.x),rz=Math.abs(b.z-a.z);points=Array.from({length:41},(_,i)=>{const t=i/40*Math.PI*2;return[a.x+Math.cos(t)*rx,a.z+Math.sin(t)*rz];});}return <group onPointerDown={click}><PitchLine points={points} color={item.color} y={.09}/></group>;}

function Scene(props:ExerciseCanvasProps){const dragging=useRef<string|null>(null);const markerMap=useMemo(()=>Object.fromEntries(props.markers.map(m=>[m.id,m])),[props.markers]);return <><color attach="background" args={["#081217"]}/><ambientLight intensity={1.25}/><directionalLight position={[4,9,5]} intensity={1.8} castShadow={props.view==="3d"}/><Pitch/><Boards/><mesh rotation={[-Math.PI/2,0,0]} position={[0,.035,0]} onPointerMove={(e:ThreeEvent<PointerEvent>)=>{if(dragging.current)props.onMove(dragging.current,THREE.MathUtils.clamp(e.point.x,-5.5,5.5),THREE.MathUtils.clamp(e.point.z,-3.5,3.5));props.onPitchPointer("move",e.point.x,e.point.z);}} onPointerUp={(e:ThreeEvent<PointerEvent>)=>{dragging.current=null;props.onPitchPointer("up",e.point.x,e.point.z);}} onPointerDown={(e:ThreeEvent<PointerEvent>)=>{props.onSelect(null);props.onPitchPointer("down",e.point.x,e.point.z);}}><planeGeometry args={[W,H]}/><meshBasicMaterial transparent opacity={0}/></mesh>{props.paths.map(p=>markerMap[p.fromId]&&markerMap[p.toId]?<AnimatedPath key={p.id} path={p} from={markerMap[p.fromId]} to={markerMap[p.toId]} playing={props.playing}/>:null)}{props.annotations.map(a=><Annotation key={a.id} item={a} erase={props.tool==="erase"} onErase={props.onEraseAnnotation}/>)}{props.markers.map(m=><Marker key={m.id} marker={m} selected={m.id===props.selectedId} view={props.view} onPointerDown={id=>{if(props.tool==="select")dragging.current=id;props.onSelect(id);}}/>)}<CameraControls view={props.view}/></>;}
export function ExerciseCanvas(props:ExerciseCanvasProps){const is2d=props.view==="2d";return <Canvas key={props.view} className="exercise-canvas" shadows={!is2d} orthographic={is2d} camera={is2d?{position:[0,10,.01],zoom:76,near:.1,far:30}:{position:[0,7.2,8.8],fov:42,near:.1,far:40}} dpr={[1,1.5]}><Scene {...props}/></Canvas>;}
