import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Circle, Eraser, Footprints, Goal, Minus, MousePointer2, Pause, Pencil, Play, Redo2, Route, Square, Sun, Type, UserRoundPlus } from "lucide-react";
import type { Team } from "../../types";
import { ExerciseCanvas } from "./ExerciseCanvas";
import { canPassBetween, type ExerciseAnnotation, type ExerciseDraft, type ExerciseMarker, type ExercisePath, type ExerciseTool, type ExerciseView } from "./exerciseTypes";

interface ExercisePlannerProps { team:Team; theme:"light"|"dark"; onBack:()=>void; onToggleTheme:()=>void; }
const STORAGE_KEY="peluutin-exercise-draft-v1";
const DRAW_TOOLS:ExerciseTool[]=["draw","line","rectangle","circle"];

function seedDraft(team:Team):ExerciseDraft{const names=team.players.map(p=>({name:p.name,number:p.number}));const fallback=["Aino","Leo","Sofia","Miro","Eeli","Noel"];const spots:Array<[number,number]>=[[-3.6,2.2],[-1.4,1.2],[-3.2,-1.2],[2.8,2],[1.3,.6],[3.3,-1.5]];const markers:ExerciseMarker[]=spots.map(([x,z],i)=>({id:`player-${i+1}`,kind:"player",team:i<3?"blue":"red",name:names[i]?.name||fallback[i],number:names[i]?.number||i+1,x,z}));markers.push({id:"ball-1",kind:"ball",name:"Pallo",x:-.5,z:.1});return{name:"Syöttö ja liike",markers,paths:[{id:"path-1",kind:"pass",fromId:"player-2",toId:"player-3"}],annotations:[],updatedAt:new Date().toISOString()};}
function loadDraft(team:Team){try{const stored=localStorage.getItem(`${STORAGE_KEY}-${team.id}`);if(!stored)return seedDraft(team);const draft=JSON.parse(stored) as ExerciseDraft;if(!Array.isArray(draft.markers)||!Array.isArray(draft.paths))return seedDraft(team);const byId=Object.fromEntries(draft.markers.map(marker=>[marker.id,marker]));return{...draft,paths:draft.paths.filter(path=>path.kind!=="pass"||(byId[path.fromId]&&byId[path.toId]&&canPassBetween(byId[path.fromId],byId[path.toId]))),annotations:Array.isArray(draft.annotations)?draft.annotations:[]};}catch{return seedDraft(team);}}

const toolItems:Array<{tool:ExerciseTool;label:string;icon:typeof MousePointer2}>=[
  {tool:"select",label:"Valitse ja siirrä",icon:MousePointer2},{tool:"player-blue",label:"Lisää sininen pelaaja",icon:UserRoundPlus},{tool:"player-red",label:"Lisää punainen pelaaja",icon:UserRoundPlus},{tool:"ball",label:"Lisää pallo",icon:Goal},{tool:"pass",label:"Syöttö",icon:Route},{tool:"run",label:"Juoksu",icon:Footprints},{tool:"draw",label:"Piirrä vapaasti",icon:Pencil},{tool:"line",label:"Suora viiva",icon:Minus},{tool:"rectangle",label:"Suorakulmio",icon:Square},{tool:"circle",label:"Ympyrä",icon:Circle},{tool:"text",label:"Lisää teksti",icon:Type},{tool:"erase",label:"Pyyhi",icon:Eraser},
];

export function ExercisePlanner({team,theme,onBack,onToggleTheme}:ExercisePlannerProps){
  const[draft,setDraft]=useState(()=>loadDraft(team));const[view,setView]=useState<ExerciseView>("3d");const[tool,setTool]=useState<ExerciseTool>("select");const[selectedId,setSelectedId]=useState<string|null>(null);const[playing,setPlaying]=useState(false);const[saveLabel,setSaveLabel]=useState("Tallennettu");const[drawingId,setDrawingId]=useState<string|null>(null);const[ink,setInk]=useState("#f6b323");const[pathError,setPathError]=useState("");
  const selected=useMemo(()=>draft.markers.find(m=>m.id===selectedId)||null,[draft.markers,selectedId]);
  useEffect(()=>{setSaveLabel("Tallennetaan…");const timer=window.setTimeout(()=>{localStorage.setItem(`${STORAGE_KEY}-${team.id}`,JSON.stringify({...draft,updatedAt:new Date().toISOString()}));setSaveLabel("Tallennettu");},350);return()=>window.clearTimeout(timer);},[draft,team.id]);
  const addMarker=(kind:ExerciseTool,x:number,z:number)=>{const id=`${kind}-${Date.now()}`,count=draft.markers.filter(m=>m.kind==="player").length+1;const marker:ExerciseMarker=kind==="ball"?{id,kind:"ball",name:"Pallo",x,z}:{id,kind:"player",team:kind==="player-red"?"red":"blue",name:`Pelaaja ${count}`,number:count,x,z};setDraft(c=>({...c,markers:[...c.markers,marker]}));setSelectedId(id);setTool("select");};
  const selectMarker=(id:string|null)=>{if(!id)return setSelectedId(null);if(tool==="erase"){setDraft(c=>({...c,markers:c.markers.filter(m=>m.id!==id),paths:c.paths.filter(p=>p.fromId!==id&&p.toId!==id)}));return;}if((tool==="pass"||tool==="run")&&selectedId&&selectedId!==id){const from=draft.markers.find(m=>m.id===selectedId),to=draft.markers.find(m=>m.id===id);if(tool==="pass"&&from&&to&&!canPassBetween(from,to)){setPathError("Syötön voi kohdistaa vain saman joukkueen pelaajalle");return;}const path:ExercisePath={id:`path-${Date.now()}`,kind:tool,fromId:selectedId,toId:id};setDraft(c=>({...c,paths:[...c.paths,path]}));setPathError("");setSelectedId(id);setTool("select");return;}setPathError("");setSelectedId(id);};
  const pitchPointer=(phase:"down"|"move"|"up",x:number,z:number)=>{
    if(phase==="down"&&(tool==="player-blue"||tool==="player-red"||tool==="ball"))return addMarker(tool,x,z);
    if(phase==="down"&&tool==="text"){const id=`annotation-${Date.now()}`;setDraft(c=>({...c,annotations:[...c.annotations,{id,kind:"text",text:"Teksti",color:ink,points:[{x,z}]}]}));setTool("select");return;}
    if(DRAW_TOOLS.includes(tool)){
      if(phase==="down"){const id=`annotation-${Date.now()}`;const item:ExerciseAnnotation={id,kind:tool as ExerciseAnnotation["kind"],color:ink,points:[{x,z},{x,z}]};setDrawingId(id);setDraft(c=>({...c,annotations:[...c.annotations,item]}));}
      else if(phase==="move"&&drawingId)setDraft(c=>({...c,annotations:c.annotations.map(a=>a.id!==drawingId?a:{...a,points:a.kind==="draw"?[...a.points,{x,z}]:[a.points[0],{x,z}]})}));
      else if(phase==="up")setDrawingId(null);
    }
  };
  const removeSelected=()=>{if(!selectedId)return;setDraft(c=>({...c,markers:c.markers.filter(m=>m.id!==selectedId),paths:c.paths.filter(p=>p.fromId!==selectedId&&p.toId!==selectedId)}));setSelectedId(null);};
  const hint=pathError||(tool==="pass"||tool==="run"?(selectedId?"Valitse reitin päätepiste":"Valitse ensin lähtöpelaaja"):view==="3d"?"Pidä Shift pohjassa liikuttaaksesi näkymää · zoomaa rullalla":"Raahaa ja sommittele kenttää");
  return <main className="exercise-shell"><div className="exercise-mobile-block"><img src="/assets/peluutin-logo.svg" alt="Peluutin"/><h1>Harjoituseditori tarvitsee suuremman näytön</h1><p>Avaa Harjoitteet tabletilla tai tietokoneella. Otteluiden peluutus toimii puhelimella normaalisti.</p><button onClick={onBack}>Takaisin otteluihin</button></div>
    <section className="exercise-desktop-app">
      <header className="exercise-header"><button className="exercise-brand" onClick={onBack} aria-label="Takaisin Peluuttimeen"><img src="/favicon.svg" alt=""/><span>Peluutin</span></button><span className="exercise-divider"/><input className="exercise-title-input" value={draft.name} onChange={e=>setDraft(c=>({...c,name:e.target.value.slice(0,60)}))} aria-label="Harjoitteen nimi"/><div className="exercise-header-actions"><span className="exercise-save-state">{saveLabel}</span><div className="exercise-view-switch"><button className={view==="2d"?"active":""} onClick={()=>setView("2d")}>2D</button><button className={view==="3d"?"active":""} onClick={()=>setView("3d")}>3D</button></div><button className="exercise-icon-button" onClick={onToggleTheme} title="Vaihda teemaa"><Sun size={18}/></button><button className="exercise-icon-button" onClick={onBack} title="Takaisin otteluihin"><ArrowLeft size={18}/></button></div></header>
      <section className="exercise-stage"><ExerciseCanvas view={view} tool={tool} markers={draft.markers} paths={draft.paths} annotations={draft.annotations} selectedId={selectedId} playing={playing} onSelect={selectMarker} onMove={(id,x,z)=>setDraft(c=>({...c,markers:c.markers.map(m=>m.id===id?{...m,x,z}:m)}))} onPitchPointer={pitchPointer} onEraseAnnotation={id=>setDraft(c=>({...c,annotations:c.annotations.filter(a=>a.id!==id)}))}/><div className="exercise-stage-hint">{hint}</div></section>
      <aside className="exercise-tools" aria-label="Harjoitteen työkalut">{toolItems.map(({tool:item,label,icon:Icon},index)=><button key={item} className={`${tool===item?"active":""} ${item==="player-red"?"red-player":""} ${[6,11].includes(index)?"tool-break":""}`} disabled={(item==="pass"||item==="run")&&!selectedId} onClick={()=>setTool(item)} title={label} aria-label={label}><Icon size={19}/></button>)}<div className="exercise-colors" aria-label="Piirrosväri">{["#f6b323","#f25f54","#4c9ee8","#45b77b","#ffffff"].map(color=><button key={color} className={ink===color?"active":""} style={{backgroundColor:color}} onClick={()=>setInk(color)} aria-label={`Valitse väri ${color}`}/>)}</div></aside>
      {selected&&<aside className="exercise-inspector"><div className="exercise-inspector-title"><span>Valittu</span><button onClick={()=>setSelectedId(null)} aria-label="Sulje">×</button></div><label>Nimi<input value={selected.name} onChange={e=>setDraft(c=>({...c,markers:c.markers.map(m=>m.id===selected.id?{...m,name:e.target.value.slice(0,28)}:m)}))}/></label>{selected.kind==="player"&&<label>Numero<input type="number" min="0" max="99" value={selected.number||0} onChange={e=>setDraft(c=>({...c,markers:c.markers.map(m=>m.id===selected.id?{...m,number:Number(e.target.value)}:m)}))}/></label>}<button className="exercise-delete-button" onClick={removeSelected}>Poista</button></aside>}
      <div className="exercise-playback"><button className={playing?"active":""} onClick={()=>setPlaying(c=>!c)}>{playing?<Pause size={16}/>:<Play size={16}/>} {playing?"Pysäytä":"Toista"}</button><span>{draft.paths.length} reittiä</span><button onClick={()=>setDraft(c=>({...c,paths:[]}))} disabled={!draft.paths.length}><Redo2 size={15}/>Tyhjennä reitit</button></div>
    </section></main>;
}
