import { Canvas, useFrame, useThree, type ThreeEvent } from "@react-three/fiber";
import { useEffect, useMemo, useRef } from "react";
import * as THREE from "three";
import { OrbitControls } from "three/examples/jsm/controls/OrbitControls.js";
import type { ExerciseAnnotation, ExerciseMarker, ExercisePath, ExerciseTool, ExerciseView } from "./exerciseTypes";

interface ExerciseCanvasProps { view:ExerciseView; tool:ExerciseTool; markers:ExerciseMarker[]; paths:ExercisePath[]; annotations:ExerciseAnnotation[]; selectedId:string|null; playing:boolean; onSelect:(id:string|null)=>void; onMove:(id:string,x:number,z:number)=>void; onPitchPointer:(phase:"down"|"move"|"up",x:number,z:number)=>void; onEraseAnnotation:(id:string)=>void; }
const W=12,H=8,LINE="#b8c8cc";

function CameraControls({view}:{view:ExerciseView}){const{camera,gl,size}=useThree();useEffect(()=>{if(view!=="3d")return;if(size.width/size.height<1.15)camera.position.set(0,9.2,12.7);const controls=new OrbitControls(camera,gl.domElement);controls.target.set(0,0,0);controls.enableDamping=true;controls.minDistance=7;controls.maxDistance=18;controls.maxPolarAngle=Math.PI/2.1;controls.update();return()=>controls.dispose();},[camera,gl,size.height,size.width,view]);return null;}

function PitchLine({points,color=LINE,y=.025}:{points:Array<[number,number]>;color?:string;y?:number}){const geometry=useMemo(()=>new THREE.BufferGeometry().setFromPoints(points.map(([x,z])=>new THREE.Vector3(x,y,z))),[points,y]);const material=useMemo(()=>new THREE.LineBasicMaterial({color,transparent:true,opacity:.96}),[color]);const line=useMemo(()=>new THREE.Line(geometry,material),[geometry,material]);useEffect(()=>()=>{geometry.dispose();material.dispose();},[geometry,material]);return <primitive object={line}/>;}
function arc(cx:number,cz:number,r:number,from:number,to:number,n=28):Array<[number,number]>{return Array.from({length:n+1},(_,i)=>{const a=from+(to-from)*i/n;return[cx+Math.cos(a)*r,cz+Math.sin(a)*r];});}
function Goal({z,flip=false}:{z:number;flip?:boolean}){const depth=flip?.48:-.48;return <group position={[0,0,z]}><PitchLine y={.13} color="#dce5e7" points={[[-.78,0],[-.78,depth],[.78,depth],[.78,0]]}/>{[-.78,.78].map(x=><mesh key={x} position={[x,.13,depth/2]}><boxGeometry args={[.035,.27,Math.abs(depth)]}/><meshStandardMaterial color="#dce5e7"/></mesh>)}<mesh position={[0,.26,depth]}><boxGeometry args={[1.6,.035,.035]}/><meshStandardMaterial color="#dce5e7"/></mesh><mesh position={[0,.13,depth]}><boxGeometry args={[1.6,.26,.015]}/><meshBasicMaterial color="#718087" wireframe transparent opacity={.65}/></mesh></group>;}

function Pitch(){const center=useMemo(()=>arc(0,0,1.03,0,Math.PI*2,56),[]);return <group><mesh rotation={[-Math.PI/2,0,0]} receiveShadow><planeGeometry args={[W,H]}/><meshStandardMaterial color="#121d22" roughness={.96}/></mesh>{Array.from({length:10},(_,i)=><mesh key={i} rotation={[-Math.PI/2,0,0]} position={[-5.4+i*1.2,.006,0]}><planeGeometry args={[1.2,H]}/><meshBasicMaterial color={i%2?"#17252a":"#101a1f"}/></mesh>)}<PitchLine points={[[-5.75,-3.75],[5.75,-3.75],[5.75,3.75],[-5.75,3.75],[-5.75,-3.75]]}/><PitchLine points={[[0,-3.75],[0,3.75]]}/><PitchLine points={center}/>{[1,-1].map(side=>{const end=side*3.75,penalty=side*2.42,goal=side*3.18,spot=side*2.72;return <group key={side}><PitchLine points={[[-2.05,end],[-2.05,penalty],[2.05,penalty],[2.05,end]]}/><PitchLine points={[[-.9,end],[-.9,goal],[.9,goal],[.9,end]]}/><mesh position={[0,.032,spot]} rotation={[-Math.PI/2,0,0]}><circleGeometry args={[.045,18]}/><meshBasicMaterial color={LINE}/></mesh><PitchLine points={arc(0,spot,.8,side>0?Math.PI*1.15:.15,side>0?Math.PI*1.85:.85)}/></group>;})}{([[-5.75,-3.75,0,Math.PI/2],[5.75,-3.75,Math.PI/2,Math.PI],[-5.75,3.75,-Math.PI/2,0],[5.75,3.75,Math.PI,Math.PI*1.5]] as Array<[number,number,number,number]>).map(([x,z,a,b],i)=><PitchLine key={i} points={arc(x,z,.18,a,b,10)}/>)}<mesh position={[0,.032,0]} rotation={[-Math.PI/2,0,0]}><circleGeometry args={[.05,18]}/><meshBasicMaterial color={LINE}/></mesh><Goal z={-3.75}/><Goal z={3.75} flip/></group>;}
function Boards(){const boards=useMemo(()=>{const r:Array<{x:number;z:number;rot:number;w:number}>=[];for(let x=-5;x<=5;x+=2)r.push({x,z:-4.08,rot:0,w:1.82},{x,z:4.08,rot:0,w:1.82});for(let z=-3;z<=3;z+=1.5)r.push({x:-6.08,z,rot:Math.PI/2,w:1.3},{x:6.08,z,rot:Math.PI/2,w:1.3});return r;},[]);return <group>{boards.map((b,i)=><mesh key={i} position={[b.x,.13,b.z]} rotation={[0,b.rot,0]}><boxGeometry args={[b.w,.28,.07]}/><meshStandardMaterial color={i%3===0?"#194263":"#162934"} emissive={i%3===0?"#0d3658":"#091820"} emissiveIntensity={.45}/></mesh>)}</group>;}

function textureFor(text:string){const canvas=document.createElement("canvas");canvas.width=320;canvas.height=88;const c=canvas.getContext("2d")!;c.font="700 28px Manrope, sans-serif";c.textAlign="center";const width=Math.min(300,c.measureText(text).width+32);c.fillStyle="rgba(6,15,21,.94)";c.roundRect((320-width)/2,5,width,48,11);c.fill();c.fillStyle="#fff";c.fillText(text,160,38);const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;return texture;}
function Marker({marker,selected,view,onPointerDown}:{marker:ExerciseMarker;selected:boolean;view:ExerciseView;onPointerDown:(id:string)=>void}){const texture=useMemo(()=>textureFor(marker.kind==="ball"?"Pallo":marker.name),[marker]);useEffect(()=>()=>texture.dispose(),[texture]);const color=marker.kind==="ball"?"#f3aa2b":marker.team==="red"?"#e14d46":"#2686d9";return <group position={[marker.x,.15,marker.z]} onPointerDown={(e:ThreeEvent<PointerEvent>)=>{e.stopPropagation();onPointerDown(marker.id);}}>{marker.kind==="ball"?<mesh castShadow={view==="3d"}><sphereGeometry args={[.145,24,24]}/><meshStandardMaterial color={color} emissive="#5b3700" emissiveIntensity={.25}/></mesh>:<><mesh castShadow={view==="3d"}><cylinderGeometry args={[.19,.19,.2,32]}/><meshStandardMaterial color={color} roughness={.4} emissive={selected?color:"#000"} emissiveIntensity={selected?.35:0}/></mesh><mesh position={[0,.105,0]} rotation={[-Math.PI/2,0,0]}><ringGeometry args={[.14,.18,32]}/><meshBasicMaterial color="#e8f1f4"/></mesh></>}{selected&&<mesh rotation={[-Math.PI/2,0,0]} position={[0,-.045,0]}><ringGeometry args={[.26,.31,36]}/><meshBasicMaterial color="#f3a712"/></mesh>}<sprite position={[0,.39,0]} scale={[1.35,.37,1]}><spriteMaterial map={texture} transparent depthTest={false}/></sprite></group>;}
function AnimatedPath({path,from,to,playing}:{path:ExercisePath;from:ExerciseMarker;to:ExerciseMarker;playing:boolean}){const pulses=useRef<Array<THREE.Mesh|null>>([]);const curve=useMemo(()=>new THREE.LineCurve3(new THREE.Vector3(from.x,.12,from.z),new THREE.Vector3(to.x,.12,to.z)),[from.x,from.z,to.x,to.z]);const color=path.kind==="pass"?"#ffb21c":"#75d7ff";useFrame(({clock})=>pulses.current.forEach((mesh,i)=>{if(mesh)mesh.position.copy(curve.getPoint(playing?((clock.elapsedTime*.48+i/3)%1):Math.min(1,i/3)));}));const direction=useMemo(()=>new THREE.Vector3(to.x-from.x,0,to.z-from.z).normalize(),[from.x,from.z,to.x,to.z]);return <group><mesh><tubeGeometry args={[curve,36,.035,8,false]}/><meshBasicMaterial color={color} transparent opacity={.9}/></mesh>{[0,1,2].map(i=><mesh key={i} ref={node=>{pulses.current[i]=node;}}><sphereGeometry args={[.085,16,16]}/><meshBasicMaterial color="#fff" toneMapped={false}/></mesh>)}<mesh position={[to.x-direction.x*.12,.13,to.z-direction.z*.12]} rotation={[-Math.PI/2,0,-Math.atan2(direction.z,direction.x)+Math.PI/2]}><coneGeometry args={[.11,.26,3]}/><meshBasicMaterial color={color}/></mesh></group>;}
function Annotation({item,erase,onErase}:{item:ExerciseAnnotation;erase:boolean;onErase:(id:string)=>void}){const click=(e:ThreeEvent<PointerEvent>)=>{if(erase){e.stopPropagation();onErase(item.id);}};if(item.kind==="text"){const texture=textureFor(item.text||"Teksti");return <sprite onPointerDown={click} position={[item.points[0]?.x||0,.16,item.points[0]?.z||0]} scale={[1.8,.5,1]}><spriteMaterial map={texture} transparent depthTest={false}/></sprite>;}const a=item.points[0],b=item.points.at(-1);if(!a||!b)return null;let points=item.points.map(p=>[p.x,p.z] as [number,number]);if(item.kind==="rectangle")points=[[a.x,a.z],[b.x,a.z],[b.x,b.z],[a.x,b.z],[a.x,a.z]];if(item.kind==="circle"){const rx=Math.abs(b.x-a.x),rz=Math.abs(b.z-a.z);points=Array.from({length:41},(_,i)=>{const t=i/40*Math.PI*2;return[a.x+Math.cos(t)*rx,a.z+Math.sin(t)*rz];});}return <group onPointerDown={click}><PitchLine points={points} color={item.color} y={.09}/></group>;}

function Scene(props:ExerciseCanvasProps){const dragging=useRef<string|null>(null);const markerMap=useMemo(()=>Object.fromEntries(props.markers.map(m=>[m.id,m])),[props.markers]);return <><color attach="background" args={["#081217"]}/><ambientLight intensity={1.25}/><directionalLight position={[4,9,5]} intensity={1.8} castShadow={props.view==="3d"}/><Pitch/><Boards/><mesh rotation={[-Math.PI/2,0,0]} position={[0,.035,0]} onPointerMove={(e:ThreeEvent<PointerEvent>)=>{if(dragging.current)props.onMove(dragging.current,THREE.MathUtils.clamp(e.point.x,-5.5,5.5),THREE.MathUtils.clamp(e.point.z,-3.5,3.5));props.onPitchPointer("move",e.point.x,e.point.z);}} onPointerUp={(e:ThreeEvent<PointerEvent>)=>{dragging.current=null;props.onPitchPointer("up",e.point.x,e.point.z);}} onPointerDown={(e:ThreeEvent<PointerEvent>)=>{props.onSelect(null);props.onPitchPointer("down",e.point.x,e.point.z);}}><planeGeometry args={[W,H]}/><meshBasicMaterial transparent opacity={0}/></mesh>{props.paths.map(p=>markerMap[p.fromId]&&markerMap[p.toId]?<AnimatedPath key={p.id} path={p} from={markerMap[p.fromId]} to={markerMap[p.toId]} playing={props.playing}/>:null)}{props.annotations.map(a=><Annotation key={a.id} item={a} erase={props.tool==="erase"} onErase={props.onEraseAnnotation}/>)}{props.markers.map(m=><Marker key={m.id} marker={m} selected={m.id===props.selectedId} view={props.view} onPointerDown={id=>{if(props.tool==="select")dragging.current=id;props.onSelect(id);}}/>)}<CameraControls view={props.view}/></>;}
export function ExerciseCanvas(props:ExerciseCanvasProps){const is2d=props.view==="2d";return <Canvas key={props.view} className="exercise-canvas" shadows={!is2d} orthographic={is2d} camera={is2d?{position:[0,10,.01],zoom:76,near:.1,far:30}:{position:[0,7.2,8.8],fov:42,near:.1,far:40}} dpr={[1,1.5]}><Scene {...props}/></Canvas>;}
